#░█████╗░██╗░░░░░██╗███╗░░░███╗░█████╗░████████╗██████╗░
#██╔══██╗██║░░░░░██║████╗░████║██╔══██╗╚══██╔══╝██╔══██╗
#███████║██║░░░░░██║██╔████╔██║██║░░██║░░░██║░░░██║░░██║
#██╔══██║██║░░░░░██║██║╚██╔╝██║██║░░██║░░░██║░░░██║░░██║
#██║░░██║███████╗██║██║░╚═╝░██║╚█████╔╝░░░██║░░░██████╔╝
#╚═╝░░╚═╝╚══════╝╚═╝╚═╝░░░░░╚═╝░╚════╝░░░░╚═╝░░░╚═════╝░
#Version: 1.8.1       Author: Computer_BR(Alisson)


#●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬●
#† ❤ † PING † ❤ †
#●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬●
PlayerListPing:
  ligado: true #Enable or disable display of players when hovering over the server's Ping in the server list.
  fakePlayers:
    - "&aJoin now"
    - "&aWe're waiting for you"
    - "&aWe have &5{online}&a/&4{max_players}"
PlayerListPing_Manutencao:
  ligado_Manutencao: true #Enable or disable display of players when hovering over the server's Ping in the server list.
  fakePlayers_Manutencao:
    - "&cServer is under maintenance"
    - "&cPlease wait until it's back"

#●▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬●
#† ❤ † CONFIGS † ❤ †
#●▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬●
FakeAumento:
  ativar: false #Enable or disable FakePlayerIncrease
  quantidade: 1 #Visual, indicate how many slots will increase when a player joins the server.
FakeOnline:
  ativar: false #Enable or disable FakeOnline.
  quantidade: 10  #Indicate how many players you want to appear in the PING before entering the server.
FakeMaximoJogadores:
  ativar: false #Enable or disable FakeMaximoJogadores.
  quantidade: 100 #Visual, number of players that will appear in the PING.
FakeMaximoJogadoresManutencao:
  ativar: true #Enable or disable FakeMaximoJogadoresManutencao.
  quantidade: 1 #Visual, number of players that will appear in the PING when the server is undergoing maintenance.
Whitelist:
  removerplayerkick: true #The setting to kick or allow the player to remain on the server when they are removed from the maintenance list.
  kickplayerativar: true #The setting to either kick or allow the player to remain on the server during maintenance, depending on whether they are on the maintenance list or not.
  naoremover:
    - "Computer_BR"
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
#† ❤ † PERMISSIONS † ❤ †
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
Permissoes:
  alimotd: "Alimotd.motd"
  perme_continuarnoservidor: "Alimotd.continuarnoservidor" #With this permission, players who are neither op nor on the whitelist will be able to stay on the server when maintenance is activated.
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
#† ❤ † Kick Manutenção † ❤ †
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
KickManutencao:
  desativar_manutencao: false #Toggle on or off when maintenance reaches the specific date indicated. "True" will turn off maintenance.
  year: 2050
  month: 2
  day: 10
  hours: 01
  minutes: 37
  kick_mensagem_entrada: #In this location, you can create a message to display when the player tries to access the server that is undergoing maintenance. Create infinite lines.
    - "&cSorry, the server is undergoing maintenance"
    - "&cWe'll be back in {hours} hours, {minutes} minutes, and {seconds} seconds"
    - "&con {date}"