name: AliMOTD
version: '${project.version}'
main: br.computer.alimotd.Alimotd
api-version: 1.16
softdepend: [ ProtocolLib ]
authors: [ Computer_BR ]
description: Meu primeio plugin, totalmente configuravel.
commands:
  manutencao:
    aliases:
      - manu
      - whitelist