#░█████╗░██╗░░░░░██╗███╗░░░███╗░█████╗░████████╗██████╗░
#██╔══██╗██║░░░░░██║████╗░████║██╔══██╗╚══██╔══╝██╔══██╗
#███████║██║░░░░░██║██╔████╔██║██║░░██║░░░██║░░░██║░░██║
#██╔══██║██║░░░░░██║██║╚██╔╝██║██║░░██║░░░██║░░░██║░░██║
#██║░░██║███████╗██║██║░╚═╝░██║╚█████╔╝░░░██║░░░██████╔╝
#╚═╝░░╚═╝╚══════╝╚═╝╚═╝░░░░░╚═╝░╚════╝░░░░╚═╝░░░╚═════╝░
#Versión: 1.0        Autor: Computer_BR(Alisson)


#●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬●
#† ❤ † PING † ❤ †
#●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬●
PlayerListPing:
  ligado: false #Activar o desactivar la visualización de jugadores al pasar el cursor del ratón sobre el Ping del servidor en la lista de servidores.
  fakePlayers:
    - "&aÚnete ahora."
    - "&a¡Te esperamos!"
    - "&aJugadores en línea &5{online}&a/&4{max_players}"
PlayerListPing_Manutencao:
  ligado_Manutencao: false #Para activar o desactivar la visualización de los jugadores del servidor, sitúe el cursor del ratón sobre Ping del servidor en la lista de servidores.
  fakePlayers_Manutencao:
    - "&cEl servidor está en mantenimiento"
    - "&cEspera hasta que termine el mantenimiento."
    - "&cBesos."

#●▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬●
#† ❤ † CONFIGURACIÓN † ❤ †
#●▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬●
FakeAumento:
  ativar: false #Activar o desactivar FakeAugmentation.
  quantidade: 1 #Visual, introduzca cuántas ranuras aumentarán cuando el jugador se una al servidor.
FakeOnline:
  ativar: false #Activar o desactivar FakeOnline.
  quantidade: 10  #Pon cuántos jugadores quieres que aparezcan en el PING, antes de unirte al servidor.
FakeMaximoJogadores:
  ativar: false #Activar o desactivar FakeMaximoPlayers.
  quantidade: 100 #Visual, número de jugadores que aparecerán en el PING.
FakeMaximoJogadoresManutencao:
  ativar: true #Activar o desactivar FakeMaximoPlayersMaintenance.
  quantidade: 1 #Visual, cantidad de jugadores que aparecerán en el PING cuando el servidor esté en mantenimiento.
Whitelist:
  removerplayerkick: true #La configuración para expulsar o permitir que el jugador permanezca en el servidor cuando se elimina de la lista de mantenimiento.
  kickplayerativar: true #La configuración para expulsar o permitir que un jugador permanezca en el servidor durante el mantenimiento, dependiendo de si está en la lista de mantenimiento o no.
  naoremover:
    - "Computer_BR"
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
#† ❤ † PERMISOS † ❤ †
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
Permissoes:
  alimotd: "Alimotd.motd"
  perme_continuarnoservidor: "Alimotd.continuarnoservidor" #Con este permiso, quien no tenga op y no esté en la lista blanca podrá permanecer en el servidor cuando se active el mantenimiento.
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
#† ❤ † Mantenimiento † ❤ †
#●▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬●
KickManutencao:
  desativar_manutencao: false #Activar o desactivar cuando llegue el mantenimiento en la fecha indicada. "True" desactivará el mantenimiento.
  year: 2050
  month: 2
  day: 10
  hours: 01
  minutes: 37
  kick_mensagem_entrada: #Aquí puedes crear un mensaje para mostrar cuando el jugador intenta acceder al servidor que está en mantenimiento. Puedes crear líneas infinitas.
    - "&cLo sentimos, el servidor está en mantenimiento"
    - "&cVolveremos en {hours} horas y {minutes} minutos y {seconds} segundos"
    - "&cen el día {date}"