name: AliMOTD
version: '1.9.0'
main: br.computer.alimotd.Alimotd
api-version: 1.16
softdepend: [ ProtocolLib ]
authors: [ Computer_BR ]
description: AliMotd, plugin de Motd com Sistema de manutenção
commands:
  manutencao:
    aliases:
      - manu
      - maintenance
      - whitelist
      - mainte